[build]
  command = "npm cache clean --force && rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"
  publish = "dist/your-app-name"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
